resources:
  - name: irc-notification-resource
    type: git
    source:
      uri: https://github.com/flavorjones/irc-notification-resource
      branch: master
  # - name: resource-docker-image
  #   type: docker-image
  #   source:
  #     username: {{dockerhub-username}}
  #     password: {{dockerhub-password}}
  #     repository: flavorjones/irc-notification-resource

jobs:
  - name: test
    plan:
      - get: irc-notification-resource
        trigger: true
      - task: make-test
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: golang
              tag: alpine
          inputs:
            - name: irc-notification-resource
          run:
            path: sh
            args: ["-c", "set -eux; cd irc-notification-resource; make test"]
